language: go

go:
  - "1.15"

env:
  - GO111MODULE=on

script:
  - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o bin/srun-mac ./cmd/srun
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/srun-linux ./cmd/srun
  - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o bin/srun.exe ./cmd/srun

deploy:
  provider: releases
  overwrite: true
  api_key: $GITHUB_TOKEN
  file:
    - bin/srun-mac
    - bin/srun-linux
    - bin/srun.exe
  skip_cleanup: true
  on:
    tags: true